import '@language-masters/components/common-styles'
import clsx from 'clsx'
import Head from 'next/head'

export const metadata = {
  title: 'Welcome to next-app',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-primary-black h-screen">
        <main
          className={clsx(`
            container
            flex
            flex-col
            items-center
            h-[100%]
          `)}
        >
          {children}
        </main>
      </body>
    </html>
  )
}
