import '@language-masters/components/common-styles'
import clsx from 'clsx'
import { ClerkProvider } from '@clerk/nextjs'
import { Header } from '@language-masters/components/common'

export const metadata = {
  title: 'Welcome to next-app',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="bg-primary-black h-screen">
          <div className="container h-full flex flex-col px-[16px]">
            <Header />
            <main
              className={clsx(`
            flex
            flex-col
            items-center
            justify-center
            grow
          `)}
            >
              {children}
            </main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}
