name: Deploy to GitHub Page from main branch
on:
  push:
    branches:
      - main
jobs:
  run-test-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          yarn install
      - name: Detect affected projects
        id: affected
        run: |
          set -x
          AFFECTED=$(yarn nx show projects --affected --type app --base=origin/main --head=HEAD)
          if [ -z "$AFFECTED" ]; then
            echo "No affected apps found."
          else
            echo "affected_apps=$AFFECTED"
            echo "::set-output name=affected_apps::$AFFECTED"
          fi

      - name: Build and Deploy react-app if affected
        if: ${{ contains(steps.affected_apps_step.outputs.affected_apps, 'react-app') }}
        run: |
          echo "Deploying affected project: $AFFECTED"
          yarn nx build-ci react-app
      - name: Deploy to Github page
        uses: JamesIves/github-pages-deploy-action@3.7.1
        if: ${{ contains(steps.affected_apps_step.outputs.affected_apps, 'react-app') }}
        with:
          ACCESS_TOKEN: ${{ secrets.LANGUAGE_MASTERS_DEPLOY  }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: dist/apps/react-app # The folder the action should deploy.
          REPOSITORY_NAME: takahirohonda/takahirohonda.github.io
          TARGET_FOLDER: language-masters-react
          CLEAN: true # Automatically remove deleted files from the deploy branch
